---
abstract: '*Mix* of Test::More + Test::Reuse + Test::Routine, with *template* system.'
author:
  - 'Renato Cron <rentocron@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300034, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-CT
requires:
  App::Prove: 0
  Data::Dumper: 0
  File::Find: 0
  File::Spec: 0
  File::Spec::Functions: 0
  Getopt::Long: 0
  Moose: 0
  Moose::Exporter: 0
  MooseX::Singleton: 0
  Pod::Usage: 0
  Test::More: 0
  YAML::Tiny: 0
  perl: 5.006
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/renatoaware/Test-CT/issues
  repository: git://github.com/renatoaware/Test-CT.git
version: 0.142
